// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class AllLiveBidsResult
    {
        public int id { get; set; }
        public string BidUserid { get; set; }
        public int? EventID { get; set; }
        public int? EventVehicleID { get; set; }
        public int? BidPrice { get; set; }
        public DateTime upadtetime { get; set; }
        public bool bidstatus { get; set; }
        public string registernumer { get; set; }
        public string chassieNumber { get; set; }
        public string name { get; set; }
        public string BrandName { get; set; }
        public string modelname { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string phonenumber { get; set; }
        public string profilepic { get; set; }
        public string allprice { get; set; }
        public string allvechimg { get; set; }
        public long? RowNum { get; set; }
        public long? TotalRows { get; set; }
    }
}
