// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class allowedlocationResult
    {
        public int Eventid { get; set; }
        public string allowedlocationdata { get; set; }
    }
}
