// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class allowedeventsResult
    {
        public string id { get; set; }
        public string allowedevent { get; set; }
        public string username { get; set; }
    }
}
