// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Approvedbid
{
    public int Id { get; set; }

    public string Delaerid { get; set; }

    public int? Eventvecid { get; set; }

    public int? Eventid { get; set; }

    public DateTime? Updatedtime { get; set; }

    public string Status { get; set; }

    public int? Bidid { get; set; }
}