// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class aspnet_Roles_GetAllRolesResult
    {
        public string RoleName { get; set; }
    }
}
