// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class AspNetUser1
{
    public string Id { get; set; }

    public bool? Status { get; set; }

    public string UserRoleId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string Profilepic { get; set; }

    public string Email { get; set; }

    public bool EmailConfirmed { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public string PhoneNumber { get; set; }

    public bool PhoneNumberConfirmed { get; set; }

    public bool TwoFactorEnabled { get; set; }

    public DateTime? LockoutEndDateUtc { get; set; }

    public bool LockoutEnabled { get; set; }

    public int AccessFailedCount { get; set; }

    public string UserName { get; set; }

    public int? StateId { get; set; }

    public int? DistrictId { get; set; }

    public int? SubDistrictId { get; set; }

    public string Adress { get; set; }

    public string TotalVehiclePermission { get; set; }

    public string Totalcategories { get; set; }

    public string CompanyName { get; set; }

    public string PanCard { get; set; }

    public string AdharCard { get; set; }

    public string PinCode { get; set; }

    public string VoterCard { get; set; }

    public DateOnly? RegisterDate { get; set; }

    public DateOnly? ActiveDate { get; set; }

    public bool? Bidpermission { get; set; }

    public int? Bidquantity { get; set; }

    public decimal? Pricelimt { get; set; }

    public string Bidstates { get; set; }

    public string Bdcategories { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }

    public bool? Isonnline { get; set; }

    public string BidEvents { get; set; }

    public string PinHash { get; set; }

    public DateTime? PinHashCreatedDate { get; set; }

    public DateTime? PinHashUpdatedDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? IsPreimum { get; set; }

    public virtual ICollection<AspnetMembership> AspnetMemberships { get; set; } = new List<AspnetMembership>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual AspNetRole1 UserRole { get; set; }
}