// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class AspNetRole1
{
    public string Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<AspNetUser1> AspNetUser1s { get; set; } = new List<AspNetUser1>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}