// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class AspnetSchemaVersion
{
    public string Feature { get; set; }

    public string CompatibleSchemaVersion { get; set; }

    public bool IsCurrentVersion { get; set; }
}