// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class AspnetPersonalizationPerUser
{
    public Guid Id { get; set; }

    public Guid? PathId { get; set; }

    public Guid? UserId { get; set; }

    public byte[] PageSettings { get; set; }

    public DateTime LastUpdatedDate { get; set; }
}