// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class AspnetApplication
{
    public string ApplicationName { get; set; }

    public string LoweredApplicationName { get; set; }

    public Guid ApplicationId { get; set; }

    public string Description { get; set; }
}