// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class AuctionEvent
{
    public int Id { get; set; }

    public string EventName { get; set; }

    public int? VehicleTypeId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string Location { get; set; }

    public int? Type { get; set; }

    public int? BidPermissionCount { get; set; }

    public int? BidAmountLimit { get; set; }

    public string Terms { get; set; }

    public bool? Status { get; set; }

    public string Allowedlocation { get; set; }

    public string BankerContact { get; set; }

    public string EmployerContact { get; set; }

    public virtual ICollection<EventPermision> EventPermisions { get; set; } = new List<EventPermision>();

    public virtual VechileType VehicleType { get; set; }
}