// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class AuctionsbidsHistory
{
    public int Id { get; set; }

    public string BidUserid { get; set; }

    public int? EventId { get; set; }

    public int? EventVehicleId { get; set; }

    public int? BidPrice { get; set; }

    public DateTime Upadtetime { get; set; }

    public bool Bidstatus { get; set; }
}