// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Bidhistory
{
    public int Id { get; set; }

    public int? Bidid { get; set; }

    public int? Eventid { get; set; }

    public int? Price { get; set; }

    public DateTime Upadtetime { get; set; }

    public bool Bidstatus { get; set; }
}