// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class BidOffer
{
    public int Id { get; set; }

    public int? Userid { get; set; }

    public int? Maxprice { get; set; }

    public int? Minprice { get; set; }

    public int? Maxquntity { get; set; }

    public int? Minquanity { get; set; }

    public DateTime? Startedatedatime { get; set; }

    public DateTime? EndDatetime { get; set; }

    public string Remarks { get; set; }
}