// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class BidPriceHistory
{
    public int Id { get; set; }

    public int? BidId { get; set; }

    public int? VehcileiD { get; set; }

    public string Userid { get; set; }

    public decimal? Price { get; set; }
}