// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class BidsDocumentsPendingResult
    {
        public int id { get; set; }
        public int? eventid { get; set; }
        public int? vecid { get; set; }
        public string doctype { get; set; }
        public string docstatus { get; set; }
        public string docurl { get; set; }
        public DateTime? updatetime { get; set; }
        public string userid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string profilepic { get; set; }
        public string name { get; set; }
        public string RegisterNumer { get; set; }
        public string ChassieNumber { get; set; }
        public string ModelName { get; set; }
        public string BrandName { get; set; }
        public string BrandlogoUrl { get; set; }
        public string allvechimg { get; set; }
        public long? RowNum { get; set; }
        public int? TotalRows { get; set; }
    }
}
