// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Bidvecdoc
{
    public int Id { get; set; }

    public int? Eventid { get; set; }

    public int? Vecid { get; set; }

    public string Doctype { get; set; }

    public string Docstatus { get; set; }

    public string Docurl { get; set; }

    public DateTime? Updatetime { get; set; }

    public string Userid { get; set; }
}