// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Brand
{
    public int Id { get; set; }

    public string BrandName { get; set; }

    public int? VechileTypeId { get; set; }

    public int? VechileSubTypeId { get; set; }

    public string BrandlogoUrl { get; set; }

    public virtual ICollection<DelersVehcile> DelersVehciles { get; set; } = new List<DelersVehcile>();

    public virtual ICollection<FreeOldVehicle> FreeOldVehicles { get; set; } = new List<FreeOldVehicle>();

    public virtual ICollection<Nessistynsurence> Nessistynsurences { get; set; } = new List<Nessistynsurence>();

    public virtual ICollection<NewVecCompare> NewVecCompares { get; set; } = new List<NewVecCompare>();

    public virtual ICollection<NewVehicle> NewVehicles { get; set; } = new List<NewVehicle>();

    public virtual ICollection<VechileModel> VechileModels { get; set; } = new List<VechileModel>();

    public virtual VechileSubType VechileSubType { get; set; }

    public virtual VechileType VechileType { get; set; }

    public virtual ICollection<VehicleRequirement> VehicleRequirements { get; set; } = new List<VehicleRequirement>();
}