// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Bulkvehcile
{
    public string Slno { get; set; }

    public string Name { get; set; }

    public string RegistrationNumber { get; set; }

    public string ChassieNumber { get; set; }

    public string VechileTypes { get; set; }

    public string VehicleSubType { get; set; }

    public string Brand { get; set; }

    public string Model { get; set; }

    public string Variet { get; set; }

    public string State { get; set; }

    public string Odomiter { get; set; }

    public string Fule { get; set; }

    public string SittingCapsity { get; set; }

    public string District { get; set; }

    public string City { get; set; }

    public string ManFuctringYear { get; set; }

    public string Onwer { get; set; }

    public bool? Rc { get; set; }

    public bool? InviceBill { get; set; }

    public string Price { get; set; }

    public string Insurence { get; set; }

    public string TaxValidity { get; set; }

    public string FitnessExphiry { get; set; }

    public string PermitValidity { get; set; }

    public int Id { get; set; }
}