// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Chassie
{
    public int Id { get; set; }

    public string Chassinumver { get; set; }

    public string Pic { get; set; }

    public string Partdiscription { get; set; }
}