// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class ChasshieDetail
{
    public int Id { get; set; }

    public int? Chassieid { get; set; }

    public string PartName { get; set; }

    public string PartValue { get; set; }

    public string PartIndicator { get; set; }

    public int? Partid { get; set; }
}