// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Chat
{
    public int Id { get; set; }

    public string ChatUser { get; set; }

    public string AdminUser { get; set; }

    public string UserChat { get; set; }

    public string AdminChat { get; set; }

    public DateTime? UserChatTime { get; set; }

    public DateTime? AdminUserChatTime { get; set; }

    public bool? Isrecivedtouser { get; set; }

    public bool? Isrecivedtoadmin { get; set; }

    public DateTime? LastSeenAdmin { get; set; }

    public DateTime? Lastseenuser { get; set; }

    public string Chatcontenttype { get; set; }

    public string Chatpath { get; set; }
}