// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Connection
{
    public int Id { get; set; }

    public int? VehicleId { get; set; }

    public string VisitorId { get; set; }

    public string SellerId { get; set; }

    public DateTime? CreatedAt { get; set; }
}