// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Country
{
    public int CountryId { get; set; }

    public string CountryName { get; set; }

    public virtual ICollection<DealerLocation> DealerLocations { get; set; } = new List<DealerLocation>();

    public virtual ICollection<DealerPoint> DealerPoints { get; set; } = new List<DealerPoint>();

    public virtual ICollection<NewVehilcePrice> NewVehilcePrices { get; set; } = new List<NewVehilcePrice>();

    public virtual ICollection<State> States { get; set; } = new List<State>();
}