// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class CSVToTableWithIDResult
    {
        public int tempid { get; set; }
        public int Id { get; set; }
        public string Data { get; set; }
    }
}
