// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class DealerCategory
{
    public int Id { get; set; }

    public string Dealerid { get; set; }

    public int? CategoryId { get; set; }
}