// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class DealerPoint
{
    public int Id { get; set; }

    public int? StateId { get; set; }

    public int? CountryId { get; set; }

    public int? DistrictId { get; set; }

    public string Latitue { get; set; }

    public string Longitude { get; set; }

    public int? CityId { get; set; }

    public virtual SubDistrict City { get; set; }

    public virtual Country Country { get; set; }

    public virtual ICollection<Dealer> Dealers { get; set; } = new List<Dealer>();

    public virtual District District { get; set; }

    public virtual State State { get; set; }
}