// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Dealersetting
{
    public int Id { get; set; }

    public string HomepageBanner { get; set; }

    public int? Userid { get; set; }

    public string Domain { get; set; }

    public string Username { get; set; }
}