// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class DealerLocation
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int DistrictId { get; set; }

    public int? CountryId { get; set; }

    public int? StateId { get; set; }

    public string Adress { get; set; }

    public string Email { get; set; }

    public string Fax { get; set; }

    public string Phone { get; set; }

    public int? VehicleId { get; set; }

    public virtual Country Country { get; set; }

    public virtual District District { get; set; }

    public virtual ICollection<NewVehicle> NewVehicles { get; set; } = new List<NewVehicle>();

    public virtual ICollection<Newvehicle1> Newvehicle1s { get; set; } = new List<Newvehicle1>();

    public virtual State State { get; set; }

    public virtual NewVehicle Vehicle { get; set; }
}