// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class District
{
    public int DistrictId { get; set; }

    public string DistrictName { get; set; }

    public int StateId { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public virtual ICollection<DealerLocation> DealerLocations { get; set; } = new List<DealerLocation>();

    public virtual ICollection<DealerPoint> DealerPoints { get; set; } = new List<DealerPoint>();

    public virtual ICollection<NewVehicle> NewVehicles { get; set; } = new List<NewVehicle>();

    public virtual ICollection<NewVehilcePrice> NewVehilcePrices { get; set; } = new List<NewVehilcePrice>();

    public virtual ICollection<Newvehicle1> Newvehicle1s { get; set; } = new List<Newvehicle1>();

    public virtual ICollection<OldVehicle> OldVehicles { get; set; } = new List<OldVehicle>();

    public virtual State State { get; set; }

    public virtual ICollection<SubDistrict> SubDistricts { get; set; } = new List<SubDistrict>();

    public virtual ICollection<VehicleRequirement> VehicleRequirements { get; set; } = new List<VehicleRequirement>();
}