// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class ExpertContent
{
    public int Id { get; set; }

    public int? Pointid { get; set; }

    public string Videourl { get; set; }

    public string Audiourl { get; set; }

    public string Img { get; set; }
}