// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Expertpoint
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Img { get; set; }
}