// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class FancyNumber
{
    public int Id { get; set; }

    public int? Stateid { get; set; }

    public int? Districtid { get; set; }

    public int? Cityid { get; set; }

    public string Fancynumber1 { get; set; }

    public string Price { get; set; }

    public string Pic { get; set; }

    public string Picdis { get; set; }

    public string OpenFor { get; set; }
}