// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class FinaceRequirement
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Conatct { get; set; }

    public string Email { get; set; }
}