// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class FreeOldVehiclenew
{
    public int Id { get; set; }

    public string FarstName { get; set; }

    public string LastName { get; set; }

    public string Emailid { get; set; }

    public string PhoneNumber { get; set; }

    public int? Districtid { get; set; }

    public int? SubDistrictid { get; set; }

    public string RegisterNumer { get; set; }

    public string ChassieNumber { get; set; }

    public string Name { get; set; }

    public int? BrandId { get; set; }

    public string VehicleType { get; set; }

    public int? ModelId { get; set; }

    public int? ManfuctringYear { get; set; }

    public string Color { get; set; }

    public string City { get; set; }

    public string Odomiter { get; set; }

    public string Price { get; set; }

    public string Fule { get; set; }

    public DateTime? PostedDate { get; set; }

    public int? CategoryId { get; set; }

    public int? SubCategoryId { get; set; }

    public int? VarietId { get; set; }

    public DateTime? InsurenceExphiryDate { get; set; }

    public bool? Rc { get; set; }

    public bool? InviceBill { get; set; }

    public DateTime? TaxValidityDate { get; set; }

    public DateTime? FitnessExphiryDate { get; set; }

    public DateTime? PermitExphiryDate { get; set; }

    public bool? Homepages { get; set; }

    public string BodyType { get; set; }

    public string Lenth { get; set; }

    public string SittingCapsity { get; set; }

    public int? CityId { get; set; }

    public string Ipaddress { get; set; }

    public int? BodyTypeId { get; set; }

    public int? BodyLenthId { get; set; }

    public int? Onwer { get; set; }

    public bool? Status { get; set; }

    public bool? IsDeleted { get; set; }

    public bool? IsoferedinBid { get; set; }
}