// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class GetAppUserVehicleInfoResult
    {
        public int id { get; set; }
        public double? Price { get; set; }
        public string ChassieNumber { get; set; }
        public string RegisterNumer { get; set; }
        public string Fule { get; set; }
        public int? ManfuctringYear { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public int? CategoryID { get; set; }
        public int? SubCategoryID { get; set; }
        public string typeName { get; set; }
        public string subTypeName { get; set; }
        public int BrandID { get; set; }
        public string BrandName { get; set; }
        public int ModelID { get; set; }
        public string ModelName { get; set; }
        public int varietID { get; set; }
        public string VarietName { get; set; }
        public int StateId { get; set; }
        public string StateName { get; set; }
        public int DistrictId { get; set; }
        public string DistrictName { get; set; }
        public int SubDistrictsId { get; set; }
        public string SubDistrictsName { get; set; }
    }
}
