// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class GetAuctionEventsResult
    {
        public int id { get; set; }
        public string EventName { get; set; }
        public string typename { get; set; }
        public int? VehicleTypeID { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public string Location { get; set; }
        public int? type { get; set; }
        public int? BidPermissionCount { get; set; }
        public int? BidAmountLimit { get; set; }
        public string terms { get; set; }
        public bool? Status { get; set; }
        public long? RowNum { get; set; }
    }
}
