// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class GetBankKitTimeLineResult
    {
        public int id { get; set; }
        public string userID { get; set; }
        public int? vehicleID { get; set; }
        public double? bidPrice { get; set; }
        public DateTime? bidTime { get; set; }
        public string Name { get; set; }
        public int? BrandID { get; set; }
        public int? ModelID { get; set; }
        public string ModelName { get; set; }
        public string BrandName { get; set; }
        public string BrandlogoUrl { get; set; }
        public string images { get; set; }
    }
}
