// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class getCompletercvecbidsResult
    {
        public int id { get; set; }
        public string BidUserid { get; set; }
        public int? EventID { get; set; }
        public int? EventVehicleID { get; set; }
        public int? BidPrice { get; set; }
        public DateTime upadtetime { get; set; }
        public bool bidstatus { get; set; }
        public string allvechimg { get; set; }
        public long? RowNum { get; set; }
        public string Name { get; set; }
        public string RegisterNumer { get; set; }
        public string ChassieNumber { get; set; }
        public int? daysleft { get; set; }
        public string rc { get; set; }
        public string kyc { get; set; }
        public string doctype { get; set; }
        public string docstatus { get; set; }
        public DateTime? docupdatetime { get; set; }
        public long? TotalRows { get; set; }
    }
}
