// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class GetDistrictsByIDResult
    {
        public int DistrictId { get; set; }
        public string DistrictName { get; set; }
        public int StateId { get; set; }
        [Column("latitude", TypeName = "decimal(18,0)")]
        public decimal? latitude { get; set; }
        [Column("longitude", TypeName = "decimal(18,0)")]
        public decimal? longitude { get; set; }
    }
}
