// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class getdisticthomepagevehcileResult
    {
        public long? RowNum { get; set; }
        public int Vid { get; set; }
        public string RegisterNumer { get; set; }
        public string Chassienumber { get; set; }
        public string vehicleName { get; set; }
        public string Fule { get; set; }
        public string StateName { get; set; }
        public int vehilceStateid { get; set; }
        public string vehicleDistricName { get; set; }
        public int vechleDistrictID { get; set; }
        public string postedusername { get; set; }
        public string UserName { get; set; }
        public string phonenumber { get; set; }
        public string Email { get; set; }
        public string posteduserStateName { get; set; }
        public string categorname { get; set; }
        public int categoryid { get; set; }
        public string BrandName { get; set; }
        public string ModelName { get; set; }
    }
}
