// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class getDealerBrandsResult
    {
        public int? Brand { get; set; }
        public string brandname { get; set; }
    }
}
