// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class GetfancyNumbersHomeFilterResult
    {
        public int id { get; set; }
        public int? stateid { get; set; }
        public int? districtid { get; set; }
        public int? cityid { get; set; }
        public string fancynumber { get; set; }
        public string Price { get; set; }
        public string pic { get; set; }
        public string picdis { get; set; }
        public string open_for { get; set; }
        public string StateName { get; set; }
        public string DistrictName { get; set; }
        public string SubDistrictsName { get; set; }
        public long? rownum { get; set; }
        public int? TotalRow { get; set; }
    }
}
