// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class GethomepageVehcileResult
    {
        public int ID { get; set; }
        public string RegisterNumer { get; set; }
        public string ChassieNumber { get; set; }
        public string Name { get; set; }
        public int? BrandID { get; set; }
        public string VehicleType { get; set; }
        public int? ModelID { get; set; }
        public int? ManfuctringYear { get; set; }
        public string Color { get; set; }
        public string City { get; set; }
        public string ODOMITER { get; set; }
        public double? Price { get; set; }
        public string Fule { get; set; }
        public DateTime? PostedDate { get; set; }
        public int? CategoryID { get; set; }
        public int? SubCategoryID { get; set; }
        public int? varietID { get; set; }
        public DateTime? InsurenceExphiryDate { get; set; }
        public bool? RC { get; set; }
        public bool? InviceBill { get; set; }
        public DateTime? TaxValidityDate { get; set; }
        public DateTime? FitnessExphiryDate { get; set; }
        public DateTime? PermitExphiryDate { get; set; }
        public bool? ISUrgentSale { get; set; }
        public bool? IsBankIt { get; set; }
        public bool? IsHotDeal { get; set; }
        public bool? ISScarp { get; set; }
        public bool? isoferedinBid { get; set; }
        public bool? Isbanner1 { get; set; }
        public bool? Isbanner2 { get; set; }
        public bool? Homepages { get; set; }
        public string BodyType { get; set; }
        public string Lenth { get; set; }
        public string SittingCapsity { get; set; }
        public string PostedByUserID { get; set; }
        public int? CityID { get; set; }
        public string ipaddress { get; set; }
        public int? BodyTypeID { get; set; }
        public int? BodyLenthID { get; set; }
        public int? Onwer { get; set; }
        public bool? status { get; set; }
        public bool? IsDeleted { get; set; }
        public int? StateID { get; set; }
        public int? DistricID { get; set; }
        public int? UserRoleid { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string URl { get; set; }
        public string ModelName { get; set; }
        public string BrandName { get; set; }
        public string catname { get; set; }
    }
}
