// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class getNerrestdealersResult
    {
        public int id { get; set; }
        public int? stateID { get; set; }
        public int? CountryID { get; set; }
        public int? DistrictID { get; set; }
        public string latitue { get; set; }
        public string longitude { get; set; }
        public int? CityID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public int? DealersPointID { get; set; }
        public int? CateGoryID { get; set; }
        public int? SubCategoryID { get; set; }
        public int? BrandID { get; set; }
        public string Brands { get; set; }
        public string Models { get; set; }
        public int? DealerID { get; set; }
        public double? distance_in_km { get; set; }
        public long? RowNum { get; set; }
        public long? TotalRows { get; set; }
    }
}
