// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class GetPointDealersResult
    {
        public long? Rownum { get; set; }
        public long? Rownum1 { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public int? DealersPointID { get; set; }
        public int? stateid { get; set; }
        public string StateName { get; set; }
        public int? DistrictID { get; set; }
        public string DistrictName { get; set; }
        public int? CityID { get; set; }
        public string SubDistrictsName { get; set; }
        public string latitue { get; set; }
        public string longitude { get; set; }
        public int? Brandid { get; set; }
        public string Brandname { get; set; }
        public int? TotalRows { get; set; }
    }
}
