// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class GetRTAOfficeAddressResult
    {
        public int id { get; set; }
        public string RTAcode { get; set; }
        public int? StateID { get; set; }
        public int? DistrictID { get; set; }
        public int? Cityid { get; set; }
        public string Address { get; set; }
        public string Emailid { get; set; }
        public string phonenumber { get; set; }
        public string statename { get; set; }
        public string DistrictName { get; set; }
        public string SubDistrictsName { get; set; }
    }
}
