// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class GetVehcileAttributeWithValueResult
    {
        public int ID { get; set; }
        public int AttributeID { get; set; }
        public int? SubAttributeID { get; set; }
        public string Name { get; set; }
        public DateTime? CreatedDate { get; set; }
        public bool? status { get; set; }
        public string SubAttributeName { get; set; }
    }
}
