// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class GetVarietsByIDResult
    {
        public int id { get; set; }
        public string VarietName { get; set; }
        public int? ModelID { get; set; }
        public bool? isdisscontinued { get; set; }
        public int? disconnectedYear { get; set; }
    }
}
