// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class GetVechileModelByIDResult
    {
        public int ID { get; set; }
        public int? BrandID { get; set; }
        public string ModelName { get; set; }
        public int? VsubtypeID { get; set; }
        public int? VtypeID { get; set; }
        public bool? isdisscontinued { get; set; }
        public int? disconnectedYear { get; set; }
    }
}
