// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class GetVecPricesResult
    {
        public int id { get; set; }
        public int? VehicleID { get; set; }
        public string Price { get; set; }
        public int? CountryID { get; set; }
        public int? StateID { get; set; }
        public int? DistrictID { get; set; }
        public int? CityID { get; set; }
        public double? exshowrommprice { get; set; }
        public double? rtoprice { get; set; }
        public double? insuranceprice { get; set; }
        public double? insurancetime { get; set; }
        public double? otherprice { get; set; }
        public double? rtopricepercentage { get; set; }
    }
}
