// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Homepagecomaprevec
{
    public int Id { get; set; }

    public int? Vehileid { get; set; }

    public bool? Status { get; set; }

    public DateTime? Istdate { get; set; }

    public DateTime? Utcdate { get; set; }

    public string Comaprevehciles { get; set; }

    public string Displayvecid { get; set; }

    public string Displayrefvecid { get; set; }
}