// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Homepageshowcase
{
    public int Id { get; set; }

    public int? Vehicleid { get; set; }

    public int? Kindid { get; set; }

    public int? Imageid { get; set; }

    public bool? Status { get; set; }

    public DateTime? Ist { get; set; }

    public DateTime? Utc { get; set; }
}