// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class HomepageVehcile
{
    public int Id { get; set; }

    public int Categoryid { get; set; }

    public int Vehicleid { get; set; }

    public DateOnly Createdate { get; set; }

    public virtual VechileType Category { get; set; }
}