// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Importanceofinsurence
{
    public int Id { get; set; }

    public string Neccesity { get; set; }

    public string Descriptionpolicy { get; set; }

    public string Depreciationslab { get; set; }

    public string Noclaimbonus { get; set; }

    public string Covernote { get; set; }

    public string Hypothecation { get; set; }

    public string Claimprocedure { get; set; }

    public string Personalaccident { get; set; }

    public string Risksnotcover { get; set; }

    public string Addingdetail { get; set; }

    public string Cancellationofinsurance { get; set; }

    public string Factorspremium { get; set; }

    public string Importanceofirda { get; set; }

    public string Companiesname { get; set; }
}