// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class IndiainCity
{
    public string Country { get; set; }

    public string City { get; set; }

    public string AccentCity { get; set; }

    public string Region { get; set; }

    public string Population { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }

    public int? Stateid { get; set; }

    public int Id { get; set; }
}