// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class InsurenseRequirement
{
    public int Id { get; set; }

    public bool? HaveInsurense { get; set; }

    public string Name { get; set; }

    public string ContactNumber { get; set; }

    public string Email { get; set; }

    public string Amount { get; set; }
}