// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Jugad
{
    public int Id { get; set; }

    public string Problem { get; set; }

    public string ViedoUrl { get; set; }

    public string ProblemHeading { get; set; }
}