// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class LandinglatestVec
{
    public int Id { get; set; }

    public int? Vehcileid { get; set; }

    public int? Imageid { get; set; }

    public DateOnly? Istdate { get; set; }

    public DateOnly? Utcdate { get; set; }

    public bool? Status { get; set; }

    public virtual VechileImage Image { get; set; }

    public virtual NewVehicle Vehcile { get; set; }
}