// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class LiveBidsResult
    {
        public int id { get; set; }
        public string BidUserid { get; set; }
        public int? EventID { get; set; }
        public int? EventVehicleID { get; set; }
        public int? BidPrice { get; set; }
        public DateTime upadtetime { get; set; }
        public bool bidstatus { get; set; }
        public string ModelName { get; set; }
        public string BrandName { get; set; }
        public string RegisterNumer { get; set; }
        public string ChassieNumber { get; set; }
        public string Name { get; set; }
        public int? BrandID { get; set; }
        public string VehicleType { get; set; }
        public int? ModelID { get; set; }
        public int? ManfuctringYear { get; set; }
        public string Color { get; set; }
        public string City { get; set; }
        public string ODOMITER { get; set; }
        public string Price { get; set; }
        public string Fule { get; set; }
        public DateTime? PostedDate { get; set; }
        public int? CategoryID { get; set; }
        public int? SubCategoryID { get; set; }
        public int? varietID { get; set; }
        public DateTime? InsurenceExphiryDate { get; set; }
        public bool? RC { get; set; }
        public bool? InviceBill { get; set; }
        public DateTime? TaxValidityDate { get; set; }
        public DateTime? FitnessExphiryDate { get; set; }
        public DateTime? PermitExphiryDate { get; set; }
        public string BodyType { get; set; }
        public string Lenth { get; set; }
        public string SittingCapsity { get; set; }
        public int? CityID { get; set; }
        public string ipaddress { get; set; }
        public int? BodyTypeID { get; set; }
        public int? BodyLenthID { get; set; }
        public int? Onwer { get; set; }
        public bool? status { get; set; }
        public bool? IsDeleted { get; set; }
        public int? StateID { get; set; }
        public int? DistricID { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public int? TotalBid { get; set; }
        public DateTime? BidEndTime { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string phonenumber { get; set; }
        public string profilepic { get; set; }
        public string allprice { get; set; }
        public string allvechimg { get; set; }
    }
}
