// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Message
{
    public int MessageId { get; set; }

    public string Message1 { get; set; }

    public string EmptyMessage { get; set; }

    public DateTime? Date { get; set; }
}