// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Nessistynsurence
{
    public int Id { get; set; }

    public bool? Isrenew { get; set; }

    public int? RegistrationYear { get; set; }

    public int? VehicletypeId { get; set; }

    public int? VehicleSubtypeId { get; set; }

    public int? BarndId { get; set; }

    public int? ModelId { get; set; }

    public int? CityId { get; set; }

    public string RegisterationNumber { get; set; }

    public DateTime? PolicyExphiryDate { get; set; }

    public string UserName { get; set; }

    public string Mobile { get; set; }

    public string Email { get; set; }

    public string Alternumber { get; set; }

    public virtual Brand Barnd { get; set; }

    public virtual SubDistrict City { get; set; }

    public virtual VechileModel Model { get; set; }

    public virtual VechileSubType VehicleSubtype { get; set; }

    public virtual VechileType Vehicletype { get; set; }
}