// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class NewSearchvecNEWResult
    {
        public int? rownum { get; set; }
        public int? RowNum1 { get; set; }
        public int? id { get; set; }
        public string name { get; set; }
        public int? modelid { get; set; }
        public int? brandid { get; set; }
        public int? cityid { get; set; }
        public int? DistricID { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public int? CategoryID { get; set; }
        public int? VArietID { get; set; }
        public int? SubCategoryID { get; set; }
        public int? TotalRows { get; set; }
    }
}
