// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class NewvecSubAttributesCategory
{
    public int Id { get; set; }

    public int? CatId { get; set; }

    public int? Attributid { get; set; }

    public string Name { get; set; }

    public virtual NewvecAttribute Attribut { get; set; }

    public virtual VechileType Cat { get; set; }

    public virtual ICollection<NewvecSubAttribute> NewvecSubAttributes { get; set; } = new List<NewvecSubAttribute>();
}