// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class NewvecSubAttribute
{
    public int Id { get; set; }

    public int? Catid { get; set; }

    public int? AttributeId { get; set; }

    public string SubAttributeName { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? SubAttCatId { get; set; }

    public virtual NewvecAttribute Attribute { get; set; }

    public virtual VechileType Cat { get; set; }

    public virtual ICollection<NewVecAttrContent> NewVecAttrContents { get; set; } = new List<NewVecAttrContent>();

    public virtual NewvecSubAttributesCategory SubAttCat { get; set; }
}