// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class NewVecAttrContent
{
    public int Id { get; set; }

    public int CatId { get; set; }

    public int AttributeId { get; set; }

    public int? SubAttributeId { get; set; }

    public string Name { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? Status { get; set; }

    public int? VehcileId { get; set; }

    public virtual NewvecAttribute Attribute { get; set; }

    public virtual VechileType Cat { get; set; }

    public virtual NewvecSubAttribute SubAttribute { get; set; }

    public virtual NewVehicle Vehcile { get; set; }
}