// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class NeWvehicleFeature
{
    public int Id { get; set; }

    public int? VehicleId { get; set; }

    public string Fueltype { get; set; }

    public string Mileage { get; set; }

    public string Enginecapacity { get; set; }

    public string Colour { get; set; }

    public string Alloywheel { get; set; }

    public string Description { get; set; }

    public virtual ICollection<NewVehicle> NewVehicles { get; set; } = new List<NewVehicle>();

    public virtual NewVehicle Vehicle { get; set; }
}