// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class OfferBid
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public int? MaxPrice { get; set; }

    public int? MinPrice { get; set; }

    public DateTime? PostedDate { get; set; }

    public int? Vechicleid { get; set; }

    public int? BidId { get; set; }

    public DateTime? StartDatetime { get; set; }

    public DateTime? Enddatetime { get; set; }

    public string Bidremarks { get; set; }

    public int? MinbidQuantity { get; set; }

    public int? MaxbidQuantity { get; set; }

    public bool? Isopen { get; set; }

    public bool? BidStatus { get; set; }
}