// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class OtpLog
{
    public int Id { get; set; }

    public string Otp { get; set; }

    public DateTime? GenrateUtc { get; set; }

    public DateTime? GenrateItc { get; set; }

    public bool? Status { get; set; }

    public int? Validitytime { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Userid { get; set; }

    public string Ipaddress { get; set; }

    public string Host { get; set; }
}