// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class PostRequirement
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Contact { get; set; }

    public string Email { get; set; }

    public string City { get; set; }

    public int? CategoryId { get; set; }

    public int? BrandId { get; set; }

    public int? ModelId { get; set; }

    public DateTime? PurchaseDate { get; set; }

    public string FinanceName { get; set; }

    public string FinanceContact { get; set; }

    public string FinanceEmail { get; set; }

    public string FinaceCity { get; set; }

    public string FinaceBudget { get; set; }

    public bool? IsInsurance { get; set; }

    public string InsuranceCompnayName { get; set; }

    public string InsuranceCompnayContact { get; set; }

    public string InsuranceCompnayEmail { get; set; }
}