// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Purchasehistory
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Itemname { get; set; }

    public string Transectionid { get; set; }

    public DateTime? IstDatetime { get; set; }

    public DateTime? UtcDatetime { get; set; }

    public decimal? Amount { get; set; }
}