// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Request
{
    public int Id { get; set; }

    public string Message { get; set; }

    public int UserRoleId { get; set; }

    public bool? Status { get; set; }
}