// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class RtafileDocument
{
    public int Id { get; set; }

    public int? FileId { get; set; }

    public string Discription { get; set; }

    public string Pic { get; set; }

    public string Audio { get; set; }

    public string Video { get; set; }

    public string Name { get; set; }

    public int? DispayNumber { get; set; }
}