// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class RtaofficeAddress
{
    public int Id { get; set; }

    public string Rtacode { get; set; }

    public int? StateId { get; set; }

    public int? DistrictId { get; set; }

    public int? Cityid { get; set; }

    public string Address { get; set; }

    public string Emailid { get; set; }

    public string Phonenumber { get; set; }
}