// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class s_showofferbidResult
    {
        public long? RowNum { get; set; }
        public string categoryname { get; set; }
        public int id { get; set; }
        public DateTime? posteddate { get; set; }
        public string Name { get; set; }
        public int? BrandID { get; set; }
        public string VehicleType { get; set; }
        public int? ModelID { get; set; }
        public double? Price { get; set; }
        public int? StateID { get; set; }
        public int? DistricID { get; set; }
        public string url { get; set; }
        public string onwerdetails { get; set; }
    }
}
