// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Safty
{
    public int Id { get; set; }

    public string Ac { get; set; }

    public string AdjustableDriverSeat { get; set; }

    public string Seattype { get; set; }

    public string AirBrakes { get; set; }

    public string FrontAxle { get; set; }

    public string FrontSuspension { get; set; }

    public string RearAxle { get; set; }

    public string RearSuspension { get; set; }

    public string Abs { get; set; }

    public string PowerSteering { get; set; }

    public string TubelessTyres { get; set; }

    public string Seatbelts { get; set; }

    public string RearAcvents { get; set; }

    public string Cdplayer { get; set; }

    public string BluetoothConnectivity { get; set; }

    public string LeatherSeats { get; set; }

    public string DriverAirbag { get; set; }

    public string PassengerAirbag { get; set; }

    public string CentralLocking { get; set; }

    public string ChildSafetyLocks { get; set; }

    public string RearCamera { get; set; }

    public string FrontBrakeType { get; set; }

    public string RearBrakeType { get; set; }

    public int? VehicleId { get; set; }

    public virtual NewVehicle Vehicle { get; set; }
}