// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class Search_SubDistrictResult
    {
        public string SubDistrictsName { get; set; }
        public int SubDistrictsId { get; set; }
    }
}
