// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class SearchBidsResult
    {
        public int Id { get; set; }
        public string userId { get; set; }
        public int? MAxPrice { get; set; }
        public int? MinPrice { get; set; }
        public DateTime? PostedDate { get; set; }
        public int? Vechicleid { get; set; }
        public int? bidID { get; set; }
        public DateTime? startDatetime { get; set; }
        public DateTime? enddatetime { get; set; }
        public string bidremarks { get; set; }
        public int? MinbidQuantity { get; set; }
        public int? MAxbidQuantity { get; set; }
        public bool? ISOpen { get; set; }
        public bool? bidStatus { get; set; }
    }
}
