// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class SellerVehicleType
{
    public int Id { get; set; }

    public string Userid { get; set; }

    public string Typeid { get; set; }

    public string OrgenstaionName { get; set; }
}