// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Sendsm
{
    public int Id { get; set; }

    public string SmsType { get; set; }

    public string Email { get; set; }

    public string Phonenumber { get; set; }

    public string Record { get; set; }
}