// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class State
{
    public int StateId { get; set; }

    public string StateName { get; set; }

    public int CountryId { get; set; }

    public string Rtacode { get; set; }

    public string Oldrtacode { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longirtude { get; set; }

    public string Pic { get; set; }

    public virtual Country Country { get; set; }

    public virtual ICollection<DealerLocation> DealerLocations { get; set; } = new List<DealerLocation>();

    public virtual ICollection<DealerPoint> DealerPoints { get; set; } = new List<DealerPoint>();

    public virtual ICollection<District> Districts { get; set; } = new List<District>();

    public virtual ICollection<FreeOldVehicle> FreeOldVehicles { get; set; } = new List<FreeOldVehicle>();

    public virtual ICollection<NewVehicle> NewVehicles { get; set; } = new List<NewVehicle>();

    public virtual ICollection<NewVehilcePrice> NewVehilcePrices { get; set; } = new List<NewVehilcePrice>();

    public virtual ICollection<Newvehicle1> Newvehicle1s { get; set; } = new List<Newvehicle1>();

    public virtual ICollection<OldVehicle> OldVehicles { get; set; } = new List<OldVehicle>();

    public virtual ICollection<VehicleRequirement> VehicleRequirements { get; set; } = new List<VehicleRequirement>();
}