// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class SubDistrict
{
    public int SubDistrictsId { get; set; }

    public string SubDistrictsName { get; set; }

    public int DistrictId { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }

    public virtual ICollection<DealerPoint> DealerPoints { get; set; } = new List<DealerPoint>();

    public virtual District District { get; set; }

    public virtual ICollection<Nessistynsurence> Nessistynsurences { get; set; } = new List<Nessistynsurence>();

    public virtual ICollection<NewVehicle> NewVehicles { get; set; } = new List<NewVehicle>();

    public virtual ICollection<Newvehicle1> Newvehicle1s { get; set; } = new List<Newvehicle1>();

    public virtual ICollection<OldVehicle> OldVehicles { get; set; } = new List<OldVehicle>();

    public virtual ICollection<VehicleRequirement> VehicleRequirements { get; set; } = new List<VehicleRequirement>();
}