// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class UsersPin
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public string Pin { get; set; }

    public DateOnly? CreatedDate { get; set; }

    public string Ipaddress { get; set; }
}