// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Variet
{
    public int Id { get; set; }

    public string VarietName { get; set; }

    public int? ModelId { get; set; }

    public bool? Isdisscontinued { get; set; }

    public int? DisconnectedYear { get; set; }

    public virtual ICollection<FreeOldVehicle> FreeOldVehicles { get; set; } = new List<FreeOldVehicle>();

    public virtual VechileModel Model { get; set; }

    public virtual ICollection<NewVecCompare> NewVecCompares { get; set; } = new List<NewVecCompare>();

    public virtual ICollection<NewVehicle> NewVehicles { get; set; } = new List<NewVehicle>();

    public virtual ICollection<Newvehicle1> Newvehicle1s { get; set; } = new List<Newvehicle1>();

    public virtual ICollection<VehicleRequirement> VehicleRequirements { get; set; } = new List<VehicleRequirement>();
}