// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class VechileSizeConfiguration
{
    public int Id { get; set; }

    public double? Width { get; set; }

    public double? Height { get; set; }

    public double? Length { get; set; }

    public int? DoorsCount { get; set; }

    public int? TotalDoors { get; set; }

    public int? Vid { get; set; }
}