// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class VechileModel
{
    public int Id { get; set; }

    public int? BrandId { get; set; }

    public string ModelName { get; set; }

    public int? VsubtypeId { get; set; }

    public int? VtypeId { get; set; }

    public bool? Isdisscontinued { get; set; }

    public int? DisconnectedYear { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual ICollection<FreeOldVehicle> FreeOldVehicles { get; set; } = new List<FreeOldVehicle>();

    public virtual ICollection<Nessistynsurence> Nessistynsurences { get; set; } = new List<Nessistynsurence>();

    public virtual ICollection<NewVecCompare> NewVecCompares { get; set; } = new List<NewVecCompare>();

    public virtual ICollection<NewVehicle> NewVehicles { get; set; } = new List<NewVehicle>();

    public virtual ICollection<Newvehicle1> Newvehicle1s { get; set; } = new List<Newvehicle1>();

    public virtual ICollection<OldVehicle> OldVehicles { get; set; } = new List<OldVehicle>();

    public virtual ICollection<Variet> Variets { get; set; } = new List<Variet>();

    public virtual ICollection<Vechile> Vechiles { get; set; } = new List<Vechile>();

    public virtual ICollection<VehicleRequirement> VehicleRequirements { get; set; } = new List<VehicleRequirement>();

    public virtual VechileSubType Vsubtype { get; set; }

    public virtual VechileType Vtype { get; set; }
}