// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class VechileType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? VechileKindId { get; set; }

    public string Image { get; set; }

    public virtual ICollection<AuctionEvent> AuctionEvents { get; set; } = new List<AuctionEvent>();

    public virtual ICollection<Brand> Brands { get; set; } = new List<Brand>();

    public virtual ICollection<DelersVehcile> DelersVehciles { get; set; } = new List<DelersVehcile>();

    public virtual ICollection<HomepageVehcile> HomepageVehciles { get; set; } = new List<HomepageVehcile>();

    public virtual ICollection<Nessistynsurence> Nessistynsurences { get; set; } = new List<Nessistynsurence>();

    public virtual ICollection<NewVecAttrContent> NewVecAttrContents { get; set; } = new List<NewVecAttrContent>();

    public virtual ICollection<NewVehicle> NewVehicles { get; set; } = new List<NewVehicle>();

    public virtual ICollection<NewvecAttribute> NewvecAttributes { get; set; } = new List<NewvecAttribute>();

    public virtual ICollection<NewvecSubAttribute> NewvecSubAttributes { get; set; } = new List<NewvecSubAttribute>();

    public virtual ICollection<NewvecSubAttributesCategory> NewvecSubAttributesCategories { get; set; } = new List<NewvecSubAttributesCategory>();

    public virtual ICollection<OldVehicle> OldVehicles { get; set; } = new List<OldVehicle>();

    public virtual VechileKind VechileKind { get; set; }

    public virtual ICollection<VechileModel> VechileModels { get; set; } = new List<VechileModel>();

    public virtual ICollection<VechileSubType> VechileSubTypes { get; set; } = new List<VechileSubType>();

    public virtual ICollection<Vechile> Vechiles { get; set; } = new List<Vechile>();

    public virtual ICollection<VehicleRequirement> VehicleRequirements { get; set; } = new List<VehicleRequirement>();
}