// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class VechileImage
{
    public int Id { get; set; }

    public int? VechileId { get; set; }

    public string Url { get; set; }

    public bool? IsMain { get; set; }

    public string Discription { get; set; }

    public string Color { get; set; }

    public string Imagetype { get; set; }

    public int? Displayorder { get; set; }

    public virtual ICollection<LandinglatestVec> LandinglatestVecs { get; set; } = new List<LandinglatestVec>();

    public virtual NewVehicle Vechile { get; set; }
}