// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class VechileSubType
{
    public int Id { get; set; }

    public int? Typeid { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Brand> Brands { get; set; } = new List<Brand>();

    public virtual ICollection<FreeOldVehicle> FreeOldVehicles { get; set; } = new List<FreeOldVehicle>();

    public virtual ICollection<Nessistynsurence> Nessistynsurences { get; set; } = new List<Nessistynsurence>();

    public virtual ICollection<NewVehicle> NewVehicles { get; set; } = new List<NewVehicle>();

    public virtual ICollection<OldVehicle> OldVehicles { get; set; } = new List<OldVehicle>();

    public virtual VechileType Type { get; set; }

    public virtual ICollection<VechileModel> VechileModels { get; set; } = new List<VechileModel>();

    public virtual ICollection<Vechile> Vechiles { get; set; } = new List<Vechile>();
}