// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class VehicleRequirement
{
    public int Id { get; set; }

    public int? TypeId { get; set; }

    public int? CategoryId { get; set; }

    public int? BrandId { get; set; }

    public int? ModelId { get; set; }

    public int? VarietId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string ContactNumber { get; set; }

    public string EmailId { get; set; }

    public int? StateId { get; set; }

    public int? DistrictId { get; set; }

    public int? CityId { get; set; }

    public DateTime? PurchaseDate { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual SubDistrict City { get; set; }

    public virtual District District { get; set; }

    public virtual VechileModel Model { get; set; }

    public virtual State State { get; set; }

    public virtual VechileType Type { get; set; }

    public virtual Variet Variet { get; set; }
}