// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class VisitorChat
{
    public int Id { get; set; }

    public string VisitorUser { get; set; }

    public string ReciverUser { get; set; }

    public string VisitorChat1 { get; set; }

    public string Reciverchat { get; set; }

    public DateTime? VisitrChatTime { get; set; }

    public DateTime? ReciverTime { get; set; }

    public bool? Isrecivedtouser { get; set; }

    public bool? Isrecivedtoadmin { get; set; }

    public DateTime? LastSeenreciver { get; set; }

    public DateTime? Lastseenvisitr { get; set; }

    public string Chatcontenttype { get; set; }

    public int? VehicleId { get; set; }

    public string Chatpath { get; set; }
}