// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Wallet
{
    public int Id { get; set; }

    public string Username { get; set; }

    public DateTime? IstupateDatetime { get; set; }

    public DateTime? UtcupdateDatetime { get; set; }

    public decimal? Amount { get; set; }
}