// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class WalletResponse
{
    public int Id { get; set; }

    public string Userid { get; set; }

    public DateTime? Istdatetime { get; set; }

    public DateTime? UtcdateTime { get; set; }

    public string Respone { get; set; }

    public string Status { get; set; }

    public string Key { get; set; }

    public string Salt { get; set; }

    public string Txnid { get; set; }

    public string Amount { get; set; }

    public string Productinfo { get; set; }

    public string Myhpayid { get; set; }
}